### ISSUE TITLE
Invalid argument on --setfan

### ISSUE THREAD

**Issue by cemcelebi** [RadeonOpenCompute/ROC-smi#18]
Hi,
I get the following error when I try this command: `rocm-smi -d 2 --setfan 65`

```
====================    ROCm System Management Interface    ====================
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rocm/bin/rocm-smi", line 1090, in <module>
    setFanSpeed(deviceList, args.setfan)
  File "/opt/rocm/bin/rocm-smi", line 878, in setFanSpeed
    if writeToSysfs(fanpath, str(fan)):
  File "/opt/rocm/bin/rocm-smi", line 314, in writeToSysfs
    return False
OSError: [Errno 22] Invalid argument
```

Wondering if this is due to the fact that I'm using GPU#2 with a riser.. 
PS:everything seems to work quite well apart from this fan setting issue.

Thank you very much!

**Comment by kentrussell** [comment]
There's a good chance, since it just uses the values from the hwmon SysFS files. Can you run these commands and let me know the results?

cat /sys/class/hwmon*/pwm1
sudo echo 65 | sudo tee /sys/class/hwmon/hwmonX/pwm1 (do that where X is each value in there, just to see if it works on any of the HW Monitors)

 Thanks!

**Comment by terorie** [comment]
I had the same problem on the R9 280x using the experimental SI support on the AMDGPU driver!

The hwmon dir path is as following:
`/sys/devices/pciXXXX:XX/XXXX:XX:XX.X/XXXX:XX:XX.X/hwmon/hwmon1`

The problem was that `pwm1_enable` was set to `0`, meaning manual fan control was disabled.

If you `echo 1 > pwm1_enable`, then `rocm-smi --setfan` will work again.

**Comment by riptl** [comment]
I was about to write that `pwm1_enable` has to be set before writing to `pwm1` before I saw the commit :P.

I can confirm that this fixes `--setfan` on R9 280x (SI) for AMDGPU.

**Comment by riptl** [comment]
Don't want to open a new issue, but could you add the option for using percentage values for fan speed? Bounds are in `pwm1_min` and `pwm1_max`.

That way you could set this on multiple cards with different min/max values.

**Comment by kentrussell** [comment]
It was a Pull Request that was made before but I forgot about it. I'll see about getting it into 1.8.1
https://github.com/RadeonOpenCompute/ROC-smi/pull/7

**Comment by kentrussell** [comment]
This is internally merged. It will be in 1.9 at the latest (trying for 1.8.1 though)
