### ISSUE TITLE
disable sudo password prompt for rocm-smi

### ISSUE THREAD

**Issue by Angel996** [RadeonOpenCompute/ROC-smi#23]
Hello.

I would like to use rocm-smi in a shell script, however it keeps prompting for sudo password. I usually solve this by setting chown root:root && chmod u+s. It works for nvidia-smi utility, for example. But in case of rocm-smi it's not working, file's got full root privileges but still asks for sudo pass.

Is there a way to work around this?

thanks.

**Comment by Angel996** [comment]
I've edited the sudoers file via visudo, but it doesn't work either... Still asking for sudo pass. Looks like rocm-smi executes some other app that needs this permission.

**Comment by jlgreathouse** [comment]
Hi @Angel996 

The reason that setting the setuid bit (chmod u+s) on rocm-smi does not do what you want is because rocm-smi is a Python script. and [setuid/setgid are ignored for runtime-interpreted scripts](https://unix.stackexchange.com/questions/364/allow-setuid-on-shell-scripts) (such as in Python, Perl, Bash, etc.).

One way to work around this difficulty is to use a tool like [super](https://www.unix.com/man-page/All/1/super/) to run the rocm-smi script. The ROCm system setup scripts that comes with [clARMOR](https://github.com/ROCm-Developer-Tools/clARMOR/tree/master/prereqs/linux_install_scripts) do this, for example. Basically, it stores off the rocm-smi script as real_rocm-smi, adds real_rocm-smi to the list of commands that super can run as root, and makes [a new script called rocm-smi](https://raw.githubusercontent.com/ROCm-Developer-Tools/clARMOR/master/prereqs/support_files/rocm-smi) that runs "super" on the real_rocm-smi script.

Here are some commands you can run to do this (this assumes that the rocm-smi you want to run is contained at `/opt/rocm/bin/rocm-smi` right now):
```
#Install ROCm-SMI so it works with SETUID
#=================================================
mkdir -p ~/Downloads/software/temp_rocm_smi
cd ~/Downloads/software/temp_rocm_smi
sudo mv /opt/rocm/bin/rocm-smi /opt/rocm/bin/real_rocm-smi
sudo chown -R root:root /opt/rocm/bin/real_rocm-smi
wget https://raw.githubusercontent.com/ROCm-Developer-Tools/clARMOR/master/prereqs/support_files/rocm-smi
sudo chown root:root ./rocm-smi
sudo chmod a+x ./rocm-smi
sudo mv ./rocm-smi /opt/rocm/bin/
sudo sh -c "echo rocm-smi /opt/rocm/bin/real_rocm-smi :video uid=0 >> /etc/super.tab"
```
At this point, anyone who is in the group "video" (which is required to be able to run GPGPU code under the newest ROCm installations) will be able to run rocm-smi without requiring a sudoer password. You can change the ":video" on the last line to limit this capability to any other group in your system.

Note that if you reinstall or upgrade ROCm, the full rocm-smi script will likely over-write the super-using replacement script and you will need to run the above series of commands again.

**Comment by kentrussell** [comment]
Unfortunately there are certain functions that require sudo, specifically reading any information from debugfs or setting values via sysfs (we need to use sudo tee for setting values, and reading from debugfs requires sudo since it's not visible to standard users). One can set up passwordless-sudo, which I know isn't ideal in most cases.
