### ISSUE TITLE
Vega FE doesn't override fan settings. 

### ISSUE THREAD

**Issue by Mandrewoid** [RadeonOpenCompute/ROC-smi#24]
If I  rocm-smi --setfan 60, then put the GPU under full load, the temp will continue to increase and the driver doesn't automatically increase fan speed. At first I thought maybe the ceiling was just high, but it did get to 98C while still running 30% fan speed. 

I know this might be a driver issue? but I'm putting issue here in the hope a smarter person than I will direct me to the right place
Thanks
Andrew

**Comment by kentrussell** [comment]
This wouldn't be the right place to do report the issue, but I'll try to explain things a bit so that you know what's going on. 

If you set the fan to 60 (60/255 = 23.5%), it will stay there. At that point, the fan is set to manual control, which won't be overridden. The hardware is designed to throttle clocks down once it gets past a certain thermal threshold, but the fan will remain low and once the temperature gets low enough, it will throttle back up again. So while you saw 98C, it was probably only running at DPM level 1, but the fan didn't raise because it was set to manual speed (via --setfan).

Resetting the fan (setting it back to auto) is the better way to go here (using --resetfan) instead of relying on the hardware to try to save the card and having it constantly fluctuate clocks to compensate for the heat.

**Comment by Mandrewoid** [comment]
you're contradicting your own words in #11

**Comment by kentrussell** [comment]
That's correct, I had to check with someone from the amdgpu team to confirm that. I was incorrect in #11. I had assumed that the fans would kick back in because I assumed that the driver had a fail-safe in there, but it doesn't. The GPU just throttles clocks down until the card is sufficiently cooler, but the fan never changes until it gets put back to automatic.

**Comment by Mandrewoid** [comment]
Sorry for being abrupt in my previous comment. I deleted it in the hope you hadn't read it yet but I guess you're just too fast at responding to issues(which I suppose is  a god problem to have)
That aside,  how do I get --resetfan ? It isn't in my version of rocm-smi
And Is there any way to edit the default fan curve to be more agressive?

**Comment by kentrussell** [comment]
It's all good, it's something that needs to be posted publicly. Someone else might get the same issue coming up and be as confused as you were by me contradicting myself.

It's available in the krussell/fixes branch, and will be available in the 1.7.1 release that is coming out soon.

The fan curve is also set by the SMU, so there isn't currently a way in the kernel to update that, it's based on thresholds defined in the firmware for the card itself.

**Comment by Mandrewoid** [comment]
Just a heads up your API is inconsistent. the setting switch is "--setfan" and the reset switch is "--resetfans"  I don't know about you but I would typo that for years

**Comment by kentrussell** [comment]
Good point. I added it as a PR but completely glossed over that. I'll deal with that now :)

**Comment by Mandrewoid** [comment]
--resetfans doesn't work, it just sets the fan to 51.76%, even when normal driver control would have fan at 15%

**Comment by kentrussell** [comment]
Hmm, peculiar. What's the GPU temperature at? Maybe there's something going on with the default value right now...

**Comment by Mandrewoid** [comment]
Gpu temp 30c

**Comment by krrk** [comment]
@Mandrewoid Since AMD is exposes the GPU through sysfs you could use [fancontrol](https://wiki.archlinux.org/index.php/Fan_speed_control#fancontrol) to setup a fan curve though I have done for one of my CPU fans I didn't like the result because there was too much hysteresis. Also if you know python write your own fan curve using the code from the rocm-smi script would make this light work since most of the helper functions are there for finding the right files in sysfs and reading and writing to them.
