### ISSUE TITLE
Sort output, please!

### ISSUE THREAD

**Issue by mistercx** [RadeonOpenCompute/ROC-smi#35]
Hi. Please, add one line to your "rocm_smi.py" into function "listDevices()":

`devicelist.sort()`

before the last line:

`return devicelist`

Thank's!

**Comment by kentrussell** [comment]
I hadn't been looking at systems with more than 2 GPUs so it never really came up in my local testing, but I see it after running the SMI on a system with 6 GPUs. After looking at how incredibly random the listing can be (since the order is determined solely by the file system and can even alternate between different FS types), I made the change. This will help people that like order (like me) and make testing it on multi-GPU systems far easier and more automatable. It's slated for 1.9.1
