### ISSUE TITLE
AvgPwr, PwrCap and GPU% are all N/A

### ISSUE THREAD

**Issue by kenshirothefist** [RadeonOpenCompute/ROC-smi#47]
AvgPwr, PwrCap and GPU% are all N/A

Ubuntu 16.04
amdgpu-pro 18.50
Radeon RX480
ROC-smi 2.0.0

> GPU   Temp   AvgPwr   SCLK    MCLK    PCLK           Fan     Perf    PwrCap   SCLK OD   MCLK OD  GPU%
0     48c    N/A      1114Mhz 2100Mhz 5.0GB, x16     60.78%  manual  N/A      0%        0%       N/A

btw: /sys/kernel/debug/dri/*/amdgpu_pm_info displays power consumption correctly

> GFX Clocks and Power:
	2100 MHz (MCLK)
	1114 MHz (SCLK)
	74.25 W (VDDC)
	14.73 W (VDDCI)
	93.150 W (max GPU)
	94.98 W (average GPU)

**Comment by jlgreathouse** [comment]
`rocm-smi` [no longer](https://github.com/RadeonOpenCompute/ROC-smi/commit/4f84634e27de7f1bd3ca43bb7850cee00d85f78c) reads power from `/sys/kernel/debug/dri`, because we want to be able to read these values without being root (see, for instance, [this bug report](https://github.com/RadeonOpenCompute/ROCm/issues/562)).

I suspect that the problem here is your version of the amdgpu-pro driver does not provide the correct sysfs entries for rocm-smi to make these readings. All of these were somewhat recent additions, and `rocm-smi` is specifically timed to match with `rock-dkms` driver releases, not `amdgpu-pro` driver releases.

As such, unless you're running the ROCm driver (or the latest upstream driver, e.g. 4.19 or 4.20) I suspect that this is not a problem with rocm-smi.
