### ISSUE TITLE
Changing maximum fan speed with automatic fan speed

### ISSUE THREAD

**Issue by SandboChang** [RadeonOpenCompute/ROC-smi#53]
I was able to use --setfan to ramp up the fan speed when it is needed, but this is all manual and I didn't want to leave them on high when the GPUs are idle.

I guess there maybe a way to use a script to keep monitoring and adjust the speed of all fans automatically, would such function be available within ROC-smi? (or it is available but I missed it?)

It maybe as simple as (naively thinking) changing the max speed of the auto setting, for example my Vega FE seems to be stuck with 40%, and R7 is stuck at 60%. It would be great if a single setting can change all of them to max at 80% or so.

**Comment by jlgreathouse** [comment]
Hi @SandboChang 

Please see [this discussion](https://github.com/RadeonOpenCompute/ROCm/issues/564#issuecomment-428069668) for a much more in-depth coverage of fan speed policies on AMD GPUs. At this time, there is no way for rocm-smi to change the default acoustic limit on your GPUs (what causes your Vega FE to stop increasing fan speed at 40% and your R7 to stop at 60%), because this is a firmware limitation informed by the BIOS on your GPU. That post describes how you could modify your graphics driver to try to change the default acoustic set-point -- though please note that AMD does not warrant any such changes as performing them incorrectly could damage your GPU.

We do not plan to modify to rocm-smi to allow such changes, and we also do not plan to modify rocm-smi to work in a daemon mode to make such changes in the background. That being said, you could write something like a background task or cronjob to use rocm-smi or sysfs writes to automatically change the manual fan speed settings. See the "Feedback-Directed Manual Control" section of my linked post.

**Comment by SandboChang** [comment]
Thanks a lot Joseph, I will try to see if I can write a small script to do it. It would be a shame to not hitting the peak performance when acoustic isn't an issue. In my case it is a workstation sitting at the corner so it doesn't really matter.
