### ISSUE TITLE
Processes using a GPU

### ISSUE THREAD

**Issue by robzor92** [RadeonOpenCompute/ROC-smi#60]
In nvidia-smi you can see what processes are running on a certain GPU, including how much memory each process allocated. I do not see it being available in rocm-smi. I see https://github.com/RadeonOpenCompute/ROC-smi/issues/42 asks specifically for memory usage, but I think more interesting for debug reasons would be which processes and list the memory used for each process. Is it on the roadmap?

**Comment by kentrussell** [comment]
Currently the PID is only stored per VM in the kernel, not per GPU. So there isn't an existing interface to make that happen, so it would need to be done in the kernel first before it can make its way up to ROCm and the SMI. I am checking to see if it's on the kernel roadmap. The kernel doesn't store how much VRAM is used per process, so that would take more work to implement.

**Comment by jlgreathouse** [comment]
I'll note that what processes are *actually* running on the GPU at any particular point in time is completely divorced from either user-space or the kernel. AMD GPUs using the ROCm software stack use a hardware scheduler (HWS) block to decide what is running during particular GPU timeslices. The kernel tells the HWS when there is a new work queue from a process, and thus the HWS knows which processes can request that work run on the GPU.

However, the HWS fully and independently chooses which of those queues to pull work from. It can run multiple kernels from any particular queue (if the software requests this), it can have multiple queues from any particular processes assigned to the GPU, and it can run kernel from multiple processes at any one time. The HWS also initiates task switching of kernels (CWSR) so that one kernel cannot take over the GPU permanently. The HWS thus decides when to stop a kernel from running, and it also makes the decisions about when to switch out queues or processes to allow other things to run.

In addition, putting work into a work queue can be done without going through the kernel at all (known as user-mode queuing). As such, while the kernel must know when a queue is first created, it does not necessarily know when any work is actually being enqueued to the GPU (and, as described above, it does not know when the GPU actually starts running that work).

So while we may be able to tell you what processes *can assign work to each GPU*, it would be much more difficult to tell you exactly what is running on each GPU at any particular point in time.

**Comment by kentrussell** [comment]
So that you don't feel completely dismayed about this request, we _are_ trying to scope the work required to make this information available. It's not guaranteed to be available or doable, but we're currently seeing if it's possible and how to make it happen if it is indeed possible to do. And thanks @jlgreathouse for that explanation and clarification!

**Comment by robzor92** [comment]
Thanks for the responses! I was able to solve the specific issue I needed this information to debug but if you are able to provide this functionality it will come in handy in the future.

**Comment by kentrussell** [comment]
It looks like we may get this into 2.6 . I'm currently working on it. Worth keeping your eyes open for it

**Comment by robzor92** [comment]
@kentrussell Was it included in 2.6? I took a look at the docs but did not find it mentioned. Anyway, looking forward to it whenever it hits.

**Comment by kentrussell** [comment]
Jeez, I didn't update the master branch when 2.6 was released... It's in the roc-2.6.x branch . I'll update master now to reflect that, but you can checkout roc-2.6.x to try it out.

I should clarify, we don't have the GPU usage or memory usage yet per-PID. Right now we've only got the PIDs associated with a compute queue right now. The other parts are on the roadmap, not sure which release yet though. Hopefully in the next 1-3 releases though

**Comment by kentrussell** [comment]
This was added in 3.3 at long last (with support for identifying the node attached to a specific process).

**Comment by kahmed10** [comment]
For anyone wanting to know how to see this info:
```
rocm-smi --showpids
```
It will look something like this:
```


============================ ROCm System Management Interface ============================
===================================== KFD Processes ======================================
KFD process information:
PID     PROCESS NAME    GPU(s)  VRAM USED       SDMA USED       CU OCCUPANCY
3722222 test_ref        0       0               0               0           
3814512 test_ref        0       0               0               0           
1168514 pt_main_thread  1       177386942464    0               4           
3714485 test_ref        0       0               0               0           
3827326 test_ref        0       0               0               0           
3730208 test_ref        0       0               0               0           
3819779 test_ref        0       0               0               0           
3726738 test_ref        0       0               0               0           
==========================================================================================
================================== End of ROCm SMI Log ===================================
```

To see which specific GPUs are being used:
```
rocm-smi --showpidgpus
```
Which will look like this:
```
============================ ROCm System Management Interface ============================
================================== GPUs Indexed by PID ===================================
PID 3722222 is using 0 DRM device(s)
PID 3814512 is using 0 DRM device(s)
PID 1168514 is using 1 DRM device(s):
0 
PID 3714485 is using 0 DRM device(s)
PID 3827326 is using 0 DRM device(s)
PID 3730208 is using 0 DRM device(s)
PID 3819779 is using 0 DRM device(s)
PID 3726738 is using 0 DRM device(s)
==========================================================================================
================================== End of ROCm SMI Log ===================================
```
Here PID 1168514 is using GPU 0.
