### ISSUE TITLE
No return-value check on --gpureset

### ISSUE THREAD

**Issue by BryantLam** [RadeonOpenCompute/ROC-smi#70]
From #69, if `relaunchAsSudo` is omitted and `rocm-smi --gpureset -d X` is used, the function always reports a successful reset even if one was not performed.

The `resetGpu` function is missing a return-value check on `getSysfsValue('gpu_reset')`.
https://github.com/RadeonOpenCompute/ROC-smi/blob/8d290c17395b4f79bfca874c31395d8f611876aa/rocm_smi.py#L1922-L1923

Without the check, `resetGpu` always reports that the reset is successful, despite `getSysfsValue` actually returning `None` at this point:
https://github.com/RadeonOpenCompute/ROC-smi/blob/8d290c17395b4f79bfca874c31395d8f611876aa/rocm_smi.py#L199-L200

I think the check inside `resetGpu` should be something like:
```python
if getSysfsValue(device[0[, 'gpu_reset') is not None:
    printLog(' ... success')
else:
    printLog(' ... failure')
```

**Comment by kentrussell** [comment]
There are a couple of problems with this:

As detailed in the comments above the gpu reset, we don't capture the return value because the function never generates a return string, so reading it returns NULL:
    # We don't capture the value because 'cat gpu_reset' just resets the
    # GPU without returning anything. 
https://github.com/RadeonOpenCompute/ROC-smi/blob/master/rocm_smi.py#L1919

So while we can capture the value from the sysfs file, it will always be NULL, so there's no point in wasting variables. It also wouldn't address your concern.

The error that you're seeing comes from sysfs, where you're trying to read a file that you have no permission for, so it returns an error.  I assume that you're getting a "Permission denied" error? This file is only accessible to root since it's part of debugfs, so the relaunchAsSudo is required. 

The getSysfsValue function only returns the "contents" of a sysfs file. These are generated by the kernel when the sysfs file is read, as defined by the functions that tie in to the different sysfs files. The gpu_recovery sysfs file generates no contents and does not return anything. We don't capture linux kernel error codes in the SMI (I also don't know if it's possible in Python, let alone how to do it), because a kernel error code is indicative of a bigger issue than something like permissions, and either indicates a kernel bug, or a userspace error.
