### ISSUE TITLE
PyPI packaging

### ISSUE THREAD

**Issue by ofek** [RadeonOpenCompute/ROC-smi#77]
Hello there! Are there plans to distribute this as a Python package on PyPI for easier installation? Many of us would really appreciate that 😄 

cc @kentrussell @pfultz2 @whchung @aaronenyeshi

**Comment by kentrussell** [comment]
No plans for it as of yet, as we're currently looking at a bit of a rework for it, but potentially after that rework

**Comment by kentrussell** [comment]
Unfortunately the rework won't quite work with pypi as-is, but it;s on the list of things to scope once we transition to the new SMI model

**Comment by ofek** [comment]
@kentrussell Why close this then?

**Comment by kentrussell** [comment]
The new SMI will be part of the rocm_smi_lib project (thus deprecating this one), and there will be some dependencies to address there. At that time, this will all be closed off. But I guess we can leave it open for reference when we do transition over from this one to the new one

**Comment by kentrussell** [comment]
Due to the LIB-backing for the CLI, this won't be easily managed. If PyPI can support distribution of the SMI CLI and can pull in the rocm_smi_lib dependency, then please open a new issue at https://github.com/RadeonOpenCompute/rocm_smi_lib, as this repo will be deprecated and all SMI CLI functionality has moved over there. Thank you!
