### ISSUE TITLE
average power and power cap

### ISSUE THREAD

**Issue by virtualroughneck** [RadeonOpenCompute/ROC-smi#89]
hi,
when i run rcom-smi i see the two power fields
1. average power 
2. Power Cap
can somebody explain me their difference. Also i want to lower my Average power consumption of my amd 580 cards without lowering the Power Cap.
All help is really appreciated
Thanks!!

**Comment by kentrussell** [comment]
1) Average power - The average power consumed by the GPU in the last sample window. This could be around 100ms or so
2) Power Cap - The maximum power usage permitted (some small spikes may exceed this value, but it should be rare)

If you want to lower power consumption without lowering the power cap, you'll need to just clock things down (sclk, mclk, socclk). Otherwise there's nothing to stop the power usage from increasing based on workload.
